### ISSUE TITLE
'load_xsensor' is not an exported object

### ISSUE THREAD

**Issue by tomassve** [Telfer/pressuRe#8]
### Problem statement

I can't use load_xsensor(). See below. There are several function not exported in package

### Probable cause

There just may be a small formatting error in the pressuRe_functions.R.

There are two spaces in 

`#'  @export
`

instead of

`#' @export
`

There problems starts from 

```
#'  @examples
#' xsensor_data <- system.file("extdata", "xsensor_data.csv", package = "pressuRe")
#' pressure_data <- load_xsensor(xsensor_data)
#'  @importFrom abind abind
#'  @export
```

### Example showing the problem

```
> library(pressuRe)
> xsensor_data <- system.file("extdata", "xsensor_data.csv", package = "pressuRe") 
> pressure_data <- load_xsensor(xsensor_data)
Error in load_xsensor(xsensor_data) : 
  could not find function "load_xsensor"
> pressuRe::load_xsensor
Error: 'load_xsensor' is not an exported object from 'namespace:pressuRe'
```

**Comment by Telfer** [comment]
Thanks for flagging this. I just pushed a fix and it works on my end. I'll send this out to CRAN with the next release. In addition, I only had one xsensor file as an example to test the package against so please let me know if you find any other issues.
